//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BildirimLog
    {
        public System.DateTime zaman { get; set; }
        public int kullnID { get; set; }
        public byte num { get; set; }
        public string SoruTuru { get; set; }
        public string icerik { get; set; }
    }
}
