//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_SESSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAM_SESSIONS()
        {
            this.EXAM_SESSION_DETAILS = new HashSet<EXAM_SESSION_DETAILS>();
        }
    
        public int EXAM_ID { get; set; }
        public int USERID { get; set; }
        public string EXAM_TITLE { get; set; }
        public int QUESTION_COUNT { get; set; }
        public int CORRECT_COUNT { get; set; }
        public int INCORRECT_COUNT { get; set; }
        public int SCORE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM_SESSION_DETAILS> EXAM_SESSION_DETAILS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
