//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int FEEDBACK_ID { get; set; }
        public int USERID { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public string FEEDBACK_TYPE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
