//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavuzSoru
    {
        public HavuzSoru()
        {
            this.SoruProfili = new HashSet<SoruProfili>();
        }
    
        public string sorutur { get; set; }
        public int havzID { get; set; }
        public string metin { get; set; }
        public string sorudenklemi { get; set; }
        public string dogrusonuc { get; set; }
        public string LaTeX { get; set; }
    
        public virtual SoruTurleri SoruTurleri { get; set; }
        public virtual ICollection<SoruProfili> SoruProfili { get; set; }
    }
}
