//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konular
    {
        public Konular()
        {
            this.KonuPuanlama = new HashSet<KonuPuanlama>();
        }
    
        public string anahtar { get; set; }
        public string yazi { get; set; }
    
        public virtual ICollection<KonuPuanlama> KonuPuanlama { get; set; }
    }
}
