//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonuPuanlama
    {
        public int kullID { get; set; }
        public string konuanahtar { get; set; }
        public Nullable<int> puanlama { get; set; }
        public Nullable<System.DateTime> sonGuncellenme { get; set; }
    
        public virtual Konular Konular { get; set; }
    }
}
