//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTurleri
    {
        public KullaniciTurleri()
        {
            this.Kullanici = new HashSet<Kullanici>();
        }
    
        public string kullAnahtar { get; set; }
        public string kullTur { get; set; }
    
        public virtual ICollection<Kullanici> Kullanici { get; set; }
    }
}
