//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Eposta = new HashSet<Eposta>();
            this.EtkilesimDegerlendirme = new HashSet<EtkilesimDegerlendirme>();
            this.SoruProfili = new HashSet<SoruProfili>();
            this.TokenKullanimi = new HashSet<TokenKullanimi>();
        }
    
        public int kimlik { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public int karsilik { get; set; }
        public string tur { get; set; }
    
        public virtual ICollection<Eposta> Eposta { get; set; }
        public virtual ICollection<EtkilesimDegerlendirme> EtkilesimDegerlendirme { get; set; }
        public virtual LoginKull LoginKull { get; set; }
        public virtual KullaniciTurleri KullaniciTurleri { get; set; }
        public virtual ICollection<SoruProfili> SoruProfili { get; set; }
        public virtual ICollection<TokenKullanimi> TokenKullanimi { get; set; }
    }
}
