//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public int LOG_ID { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_LEVEL { get; set; }
        public string MESSAGE { get; set; }
        public int USERID { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
