//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeptunDBEntities : DbContext
    {
        public NeptunDBEntities()
            : base("name=NeptunDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BildirimLog> BildirimLog { get; set; }
        public DbSet<Eposta> Eposta { get; set; }
        public DbSet<EtkilesimDegerlendirme> EtkilesimDegerlendirme { get; set; }
        public DbSet<HavuzSoru> HavuzSoru { get; set; }
        public DbSet<Konular> Konular { get; set; }
        public DbSet<KonuPuanlama> KonuPuanlama { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<KullaniciTurleri> KullaniciTurleri { get; set; }
        public DbSet<LoginKull> LoginKull { get; set; }
        public DbSet<SablonSoru> SablonSoru { get; set; }
        public DbSet<SistemikHataLog> SistemikHataLog { get; set; }
        public DbSet<SoruProfili> SoruProfili { get; set; }
        public DbSet<SoruTurleri> SoruTurleri { get; set; }
        public DbSet<TokenKullanimi> TokenKullanimi { get; set; }
    }
}
