//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NEPTUN_DBEntities : DbContext
    {
        public NEPTUN_DBEntities()
            : base("name=NEPTUN_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKMARKED_QUESTIONS> BOOKMARKED_QUESTIONS { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<LOGS> LOGS { get; set; }
        public virtual DbSet<QUESTION_POOL> QUESTION_POOL { get; set; }
        public virtual DbSet<SUBTOPICS> SUBTOPICS { get; set; }
        public virtual DbSet<TOPICS> TOPICS { get; set; }
        public virtual DbSet<USER_SCORES> USER_SCORES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<WRONG_ANSWERED_QUESTIONS> WRONG_ANSWERED_QUESTIONS { get; set; }
    }
}
