//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeptunDB : DbContext
    {
        public NeptunDB()
            : base("name=NeptunDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BildirimLog> BildirimLog { get; set; }
        public virtual DbSet<Eposta> Eposta { get; set; }
        public virtual DbSet<EtkilesimDegerlendirme> EtkilesimDegerlendirme { get; set; }
        public virtual DbSet<HavuzSoru> HavuzSoru { get; set; }
        public virtual DbSet<Konular> Konular { get; set; }
        public virtual DbSet<KonuPuanlama> KonuPuanlama { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciTurleri> KullaniciTurleri { get; set; }
        public virtual DbSet<LoginKull> LoginKull { get; set; }
        public virtual DbSet<SablonSoru> SablonSoru { get; set; }
        public virtual DbSet<SistemikHataLog> SistemikHataLog { get; set; }
        public virtual DbSet<SoruProfili> SoruProfili { get; set; }
        public virtual DbSet<SoruTurleri> SoruTurleri { get; set; }
        public virtual DbSet<TokenKullanimi> TokenKullanimi { get; set; }
    }
}
