//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_POOL
    {
        public int POOL_ID { get; set; }
        public int TOPIC_ID { get; set; }
        public int SUBTOPIC_ID { get; set; }
        public string QUESTION_TEXT { get; set; }
        public string LATEX_TEXT { get; set; }
        public string CORRECT_ANSWER { get; set; }
        public string WRONG_ANSWERS { get; set; }
    
        public virtual SUBTOPICS SUBTOPICS { get; set; }
        public virtual TOPICS TOPICS { get; set; }
    }
}
