//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SablonSoru
    {
        public string sorutur { get; set; }
        public int sablID { get; set; }
        public string metin { get; set; }
        public string sorudenklemi { get; set; }
        public string LaTeX { get; set; }
    
        public virtual SoruTurleri SoruTurleri { get; set; }
    }
}
