//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruProfili
    {
        public int kullId { get; set; }
        public string soruTur { get; set; }
        public int havzID { get; set; }
        public Nullable<bool> dogruluk { get; set; }
    
        public virtual HavuzSoru HavuzSoru { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
