//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruTurleri
    {
        public SoruTurleri()
        {
            this.HavuzSoru = new HashSet<HavuzSoru>();
            this.SablonSoru = new HashSet<SablonSoru>();
        }
    
        public string anahtar { get; set; }
        public string tur_karsilik { get; set; }
    
        public virtual ICollection<HavuzSoru> HavuzSoru { get; set; }
        public virtual ICollection<SablonSoru> SablonSoru { get; set; }
    }
}
