//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptunMathWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenKullanimi
    {
        public int kullID { get; set; }
        public int oturum { get; set; }
        public Nullable<double> girdiTOKEN { get; set; }
        public Nullable<double> ciktiTOKEN { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
